version: '3.8'
run: cd 
services:
  eureka-server:
    build: 
      context: ./eureka-service
      dockerfile: Dockerfile
    restart: unless-stopped

  health:
    build:
      context: ./health-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - eureka-server
  
  lodging:
    build: 
      context: ./lodging-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - eureka-server
  
  matches:
    build: 
      context: ./matches-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - eureka-server
  
  travel:
    build: 
      context: ./travel-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - eureka-server

  gateway:
    build:
      context: ./gateway-service
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - eureka-server
      - health
      - lodging
      - matches
      - travel
