spring:
    cloud:
        gateway:
          routes:
          - id: package-admin-service
            uri: lb://package-admin-service
            predicates:
              - Path=/api/v1/admin/package/**
            filters:
              - StripPrefix=4
          - id: health-insurance-service
            uri: lb://health-insurance-service
            predicates:
              - Path=/api/v1/health/**
            filters:
              - StripPrefix=3
          - id: lodging-service
            uri: lb://lodging-service
            predicates:
              - Path=/api/v1/lodging/**
            filters:
              - StripPrefix=3
          - id: match-service
            uri: lb://match-service
            predicates:
              - Path=/api/v1/match/**
            filters:
              - StripPrefix=3              
          - id: travel-service
            uri: lb://travel-service
            predicates:
              - Path=/api/v1/travel/**
            filters:
              - StripPrefix=3      
          - id: payment-service
            uri: lb://payment-service
            predicates:
              - Path=/api/v1/payment/**
            filters:
              - StripPrefix=3 
      